# https://pre-commit.com for more information
default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
