name: CI test pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - v*.*.*
  pull_request:
    branches:
      - main
      - develop
      - project/*
      - v*.*.*
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # Required for Codecov to comment on pull requests

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23', '1.24']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: go.mod

      - name: Install dependencies
        run: |
          go mod verify
          go mod download

      - name: Run pre-commit hooks
        uses: pre-commit/action@main
        with:
          extra_args: --all-files

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1

      - name: Run tests with coverage
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out -o=coverage.txt
          cat coverage.txt

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
